# Generated by Django 3.1.3 on 2020-11-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201129_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default='29 November 2020 01:32:03'),
        ),
    ]
